# ============================
# API Keys (use .env for secrets ideally)
# ============================
api_key: YOUR_API_KEY
api_secret: YOUR_API_SECRET

# ============================
# General Risk Parameters
# ============================
risk_per_trade: 0.01           # Fraction of capital risked per trade
max_drawdown: 0.2              # Portfolio-level max drawdown
lot_size: 50
initial_balance: 100000

# ============================
# Trading Configuration
# ============================
trading:
  mode: "paper"                # backtest | paper | live
  broker: "zerodha"
  initial_balance: 100000
  instruments: [256265, 260105]  # NIFTY=256265, BANKNIFTY=260105
  poll_interval: 5             # seconds between data fetch

market:
  open: "09:15:00"
  close: "15:30:00"

# ============================
# Logging
# ============================
logging:
  level: "INFO"
  logfile: "logs/trading.log"

# ============================
# Risk Manager + Circuit Breaker
# ============================
risk:
  max_position_size: 500
  max_daily_loss: 5000
  max_drawdown: 0.2
  max_consecutive_losses: 5
  stop_on_loss: true
  cool_off_minutes: 15

# ============================
# Execution Engine
# ============================
execution:
  max_retries: 3
  sleep_between_retries: 2
  slippage: 0.001              # 0.1% slippage tolerance

# ============================
# Options Optimizer
# ============================
options_optimizer:
  min_volume: 1000
  min_oi: 5000
  lot_size: 50

# ============================
# RL Allocator
# ============================
rl_allocator:
  strikes: [-100, 0, 100]      # offsets from ATM
  expiries: ["weekly", "monthly"]
  window_size: 30

# ============================
# Ensemble Settings
# ============================
ensemble:
  enabled: true
  weights:
    lstm: 0.4
    transformer: 0.4
    rl_agent: 0.2
