api_key: YOUR_API_KEY
api_secret: YOUR_API_SECRET
risk_per_trade: 0.01
max_drawdown: 0.2
instrument_token: 738561   # NIFTY 50
lot_size: 50
initial_balance: 100000

trading:
  mode: "paper"         
  broker: "zerodha"
  initial_balance: 2000000

market:
  open: "09:15:00"
  close: "15:30:00"

risk:
  max_position_size: 500
  max_daily_loss: 50000
  max_drawdown: 100000
  stop_on_loss: true
  cool_off_minutes: 30
  max_consecutive_losses: 3

options_optimizer:
  enabled: true
  strike_selection: "dynamic"    # ATM, ITM, OTM, dynamic
  expiry_selection: "dynamic"    # weekly, monthly, dynamic
  max_open_positions: 5

rl_allocator:
  strikes: [-200, 0, 200]        # ITM, ATM, OTM
  expiries: ["weekly", "monthly"]
  timesteps: 50000

logging:
  level: "INFO"
  logfile: "logs/trading.log"

backtest:
  slippage_pct: 0.001   # 0.1% slippage
  fee_per_order: 20     # ₹20 brokerage/fees
  broker_fees: "zerodha"  # zerodha, ibkr, angelone
